AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/seeds.rb
    - db/migrate/*
    - config/initializers/backtrace_silencers.rb
    - config/environments/*
    - config/application.rb
    - bin/webpack-dev-server
    - app/models/application_record.rb
    - app/mailers/application_mailer.rb
    - app/helpers/application_helper.rb
    - app/controllers/application_controller.rb
    - Gemfile

Metrics/LineLength:
  Max: 100